spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/collabspace}
    username: ${SPRING_DATASOURCE_USERNAME:collabspace}
    password: ${SPRING_DATASOURCE_PASSWORD:collabspace}
